// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQLVZ6Nhro5N-eMy7Qwg3BjNQysMKlW80',
    appId: '1:801790064493:web:c771deb67c24ab4dd70c64',
    messagingSenderId: '801790064493',
    projectId: 'frozenf',
    authDomain: 'frozenf.firebaseapp.com',
    storageBucket: 'frozenf.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAp7Zxzv9PWRRMYgaoethm1j8xt0bFVZYY',
    appId: '1:801790064493:android:3dd78cf46a3bcbfad70c64',
    messagingSenderId: '801790064493',
    projectId: 'frozenf',
    storageBucket: 'frozenf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBd1QngmEEy2k21mR8NLK41NSiuAjd4hdo',
    appId: '1:801790064493:ios:152eb8aad6acb5cfd70c64',
    messagingSenderId: '801790064493',
    projectId: 'frozenf',
    storageBucket: 'frozenf.appspot.com',
    iosClientId: '801790064493-8d18ttvesphq0dkl6qsgalila80tl3pm.apps.googleusercontent.com',
    iosBundleId: 'com.romanmatla.frozenFood',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBd1QngmEEy2k21mR8NLK41NSiuAjd4hdo',
    appId: '1:801790064493:ios:152eb8aad6acb5cfd70c64',
    messagingSenderId: '801790064493',
    projectId: 'frozenf',
    storageBucket: 'frozenf.appspot.com',
    iosClientId: '801790064493-8d18ttvesphq0dkl6qsgalila80tl3pm.apps.googleusercontent.com',
    iosBundleId: 'com.romanmatla.frozenFood',
  );
}
